name       : libsmbios
version    : 2.3.3
release    : 1
source     :
    - https://github.com/dell/libsmbios/archive/v2.3.3.tar.gz : 272ba8c9fa4a468938b8fa81b23a09c72acc97371f3be7c882bb222c1ae7157d
license    : 
    - GPL-2.0
    - OSL-2.1
component  : system.boot
summary    : Library for interacting with Dell SMBIOS tables
description: |
     libsmbios provides a library to interface with the SMBIOS tables. It also provides extensions for proprietary methods of interfacing with Dell specific SMBIOS tables.
builddeps  :
    - doxygen
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    # Headers needed by fwupdate
    install -dm00755 $installdir/usr/include/
    cp -a $workdir/src/include/* $installdir/usr/include/
    cp -a $workdir/out/public-include/* $installdir/usr/include/
